### PR TITLE
Add code for metrics

### PR DESCRIPTION
**Pull request by saurabhmj**
Update extract history script to accommodate new structure

Add a Jupyter Notebook to calculate metrics

### CODE REVIEW

**Comment by rscnt** [comment]
LGTM.

We can ignore the black formatter feedback if you want.

**Comment by rscnt** [comment]
Also, there's a new `percentages_for_hospitalizations.csv` file is that something we are going to be generating daily?

**Comment by saurabhmj** [comment]
> Also, there's a new `percentages_for_hospitalizations.csv` file is that something we are going to be generating daily?

Yes, this is required for imputing hospitalizations. We generate random pecentages from 12% to 16% for every day. This file stores percentage values for dates, so that we can regenrate the same results every time.

**Comment by saurabhmj** [comment]
> LGTM.
> 
> We can ignore the black formatter feedback if you want.

Is there a way to preview what the formatter would want to change?

**Comment by rscnt** [comment]
You can run the black formatter locally and use the `--diff` flag to just display the changes.

https://pypi.org/project/black/ :

```
 --diff                          Don't write the files back, just output a
                                  diff for each file on stdout.
```

**Comment by rscnt** [comment]
you wold be running something like:

```sh
pipenv run black --diff .
```

**Pull request merged**
